services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: gestion_citas_medicas-server
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/gestion-citas-medicas
    depends_on:
      - mongo
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: gestion_citas_medicas-client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo:4.2
    container_name: gestion_citas_medicas-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: