version: "3.8"

services:
  backend:
    container_name: gestion_citas_medicas-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "3030:3030"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/gestion-citas-medicas
    depends_on:
      - mongo

  frontend:
    container_name: gestion_citas_medicas-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:4.2
    container_name: gestion_citas_medicas-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: gestion_citas_medicas-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=Admin
      - ME_CONFIG_BASICAUTH_PASSWORD=Admin
    depends_on:
      - mongo

volumes:
  mongo-data: